# Generated by Django 2.2.7 on 2019-12-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
