# Generated by Django 2.2.7 on 2019-12-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='temp',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
