# Generated by Django 2.2.7 on 2019-12-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='temp',
        ),
    ]
