# Generated by Django 3.0 on 2019-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='theater',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
