# Generated by Django 3.0 on 2019-12-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20191210_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='ramainSeat',
            field=models.CharField(default='좌석없음', max_length=15),
            preserve_default=False,
        ),
    ]
