# Generated by Django 3.0 on 2019-12-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_timetable_ramainseat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='playinfo',
            new_name='playInfo',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='ramainSeat',
            new_name='remainSeat',
        ),
        migrations.AddField(
            model_name='timetable',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
